version: "3.7" # 这个是配置文件的版本，不同的版本号声明方式会有细微的不同
services:
    demo:
        container_name: my-docker
        image: szp666/beiyu:latest
        ports:
            - "8082:80"
        restart: on-failure
