language: node_js
node_js:
  - "12"
services:
  - docker

before_install:
  - yarn install
#   - composer config --global github-oauth.github.com "$tokenForTravis"

script:
  - yarn run build
  - sudo docker build -t szp666/beiyu:latest .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - sudo docker push szp666/beiyu:latest
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $tokenForTravis  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master