language: node_js
node_js:
  - "12"
services:
  - docker

before_install:
  - yarn install

script:
  - yarn run build
  - sudo docker build -t szp666/beiyu:latest .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - sudo docker push szp666/beiyu:latest
# after_success:
#   - docker login --username=username -p="password" dockerhub
#   - docker push dockerhub:latest
#   - chmod 600 id_rsa
#   - scp -o "StrictHostKeyChecking no" -i id_rsa docker-compose.yml ubuntu@ip:/home/ubuntu/docker/
#   - ssh -o "StrictHostKeyChecking no" -i id_rsa ubuntu@ip "cd /home/ubuntu/docker/;sudo docker-compose -f docker-compose.yml pull;sudo docker-compose -f docker-compose.yml up -d;exit"
  
