version: "3.8"
services: 
    web:
        stdin_open: true
        build: 
            context: .
            dockerfile: Dockerfile.dev
        ports: 
            - "5001:5001"
        volumes: 
            - "/app/node_modules"
            - "./:/app"
